#!/bin/bash
clear
echo -e "\033[1;33mOpciones de usuarios:\033[1;30m
1) Borrar usuario
2) Borrar y desconectar todos los usuarios
3) Desconectar todos los usuarios\033[0m"
read -p ": " option
 if [ $option -eq 1 ]; then
 read -p "Cual es el nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "El usuario no exixte"
 exit
 fi
 userdel --force $name > /dev/null 2>/dev/null
 echo "Usuario $name fue borrado"
 exit
 fi

 if [ $option -eq 2 ]; then
 read -p "Cual es el nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 userdel $name 1>/dev/null 2>/dev/null
 echo "Usuario $name fue desconectado y borrado"
 exit
 fi

 if [ $option -eq 3 ]; then
 read -p "Cual es el nombre del usuario: " name
 if [ $(cat /etc/passwd |grep "^$name:" |wc -l) -eq 0 ]; then
 echo "Usuario no existe"
 exit
 fi
 pids=$(ps -u $name |awk {'print $1'})
 kill "$pids" >/dev/null 2>/dev/null
 echo "Usuario $name fue detenido"
 exit
 fi
